import java.io.*;

public class Main {
    public static void main(String[] args) {
        int numOfArgs = args.length;
        Mandelbrot mandelbrot = new Mandelbrot();

    }
}

/*if( args[0].toLowerCase().equals("mandelbrot") ){
            System.out.println(args[0]);
        }
        else if( args[0].toLowerCase().equals("julia") ) {
            System.out.println(args[0]);
        }
        else{
            System.out.println("Input a valid Fractal set");
        }*/
        
        /*double x=4;
        double y=3;
        double a=1;
        double b=-1;
        

        Complex c1 = new Complex( x, y );
        Complex c2 = new Complex( a, b );
        double r1 = Complex.absolute( c1 );
        double r2 = Complex.absolute( c2 );
        Complex c3 = Complex.addition( c1, c2 );
        Complex c4 = Complex.square( c1 );
        Complex c5 = Complex.square( c2 );

        System.out.println(r1);
        System.out.println(r1);
        System.out.println("Addition " + c3.getReal() + " " + c3.getImag() );
        System.out.println("sq c1 " + c4.getReal() + " " + c4.getImag() );
        System.out.println("sq c2 " + c5.getReal() + " " + c5.getImag() );
        */